# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Run redis to test pinserver with redis backend
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle==2.5.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pycodestyle
      run: |
        pycodestyle --max-line-length=100 *.py test/*.py

    - name: Test with filesystem backend
      run: |
        cp test_keys/* ../
        cd ..
        python -m unittest -v
      env:
        PINSERVER_PORT: 1234

    - name: Test with Redis backend
      run: |
        cp test_keys/* ../
        cd ..
        python -m unittest -v
      env:
        PINSERVER_PORT: 1234
        REDIS_HOST: localhost
        REDIS_PORT: 6379

